In [ ]:
import torch
import einops

In [ ]:
torch.arange(0, 3, dtype=torch.float32).unsqueeze(1)

In [ ]:
a = einops.rearrange(torch.arange(0, 100), '(a b) -> a b', a=5, b=20)
a

In [ ]:
a[:, 0::2]

In [ ]:

div_term = torch.exp(torch.arange(0, 100, 2) * (-torch.log(torch.tensor(10000.0)) / 100))

In [ ]:
div_term.shape

In [ ]:
pe = torch.ones(1, 6, 100)
x = torch.zeros(32, 6, 100)

In [ ]:
x = x + pe[:, :x.shape[1], :]

In [ ]:
torch.sqrt(torch.tensor(100, dtype=torch.float32))

In [ ]:
a = 3
assert isinstance(a, float), 'wrong type hyperparameter'

In [1]:
import math
import torch

def calculate_even_pos(pos, i):
    return torch.sin(pos / (10000 ** (2 * i / 512)))

def calculate_odd_pos(pos, i):
    return torch.cos(pos / (10000 ** (2 * i / 512)))

In [2]:
x = torch.zeros(12, 512)
x.shape

torch.Size([12, 512])

In [3]:
a = torch.arange(0, 512)
10000 ** (2 * ( a[::2] // 2) / 512)

tensor([1.0000e+00, 1.0366e+00, 1.0746e+00, 1.1140e+00, 1.1548e+00, 1.1971e+00,
        1.2409e+00, 1.2864e+00, 1.3335e+00, 1.3824e+00, 1.4330e+00, 1.4855e+00,
        1.5399e+00, 1.5963e+00, 1.6548e+00, 1.7154e+00, 1.7783e+00, 1.8434e+00,
        1.9110e+00, 1.9810e+00, 2.0535e+00, 2.1288e+00, 2.2067e+00, 2.2876e+00,
        2.3714e+00, 2.4582e+00, 2.5483e+00, 2.6416e+00, 2.7384e+00, 2.8387e+00,
        2.9427e+00, 3.0505e+00, 3.1623e+00, 3.2781e+00, 3.3982e+00, 3.5227e+00,
        3.6517e+00, 3.7855e+00, 3.9242e+00, 4.0679e+00, 4.2170e+00, 4.3714e+00,
        4.5316e+00, 4.6976e+00, 4.8697e+00, 5.0481e+00, 5.2330e+00, 5.4247e+00,
        5.6234e+00, 5.8294e+00, 6.0430e+00, 6.2643e+00, 6.4938e+00, 6.7317e+00,
        6.9783e+00, 7.2339e+00, 7.4989e+00, 7.7737e+00, 8.0584e+00, 8.3536e+00,
        8.6596e+00, 8.9769e+00, 9.3057e+00, 9.6466e+00, 1.0000e+01, 1.0366e+01,
        1.0746e+01, 1.1140e+01, 1.1548e+01, 1.1971e+01, 1.2409e+01, 1.2864e+01,
        1.3335e+01, 1.3824e+01, 1.4330e+

In [4]:
div_term = 1 /10000. ** (2 * ( a[::2] // 2) / 512)
div_term = torch.exp(torch.arange(0, 512, 2).float() * (-math.log(10000.0) / 512))

In [5]:
x.shape

torch.Size([12, 512])

In [6]:
pos = torch.arange(0, 12, dtype=int)
pos.shape

torch.Size([12])

In [7]:
div_term.unsqueeze(0).shape

torch.Size([1, 256])

In [8]:
pos.unsqueeze(1).shape

torch.Size([12, 1])

In [9]:
x[pos, 0::2].shape

torch.Size([12, 256])

In [10]:
div_term = torch.exp(torch.arange(0, 512, 2).float() * (-math.log(10000.0) / 512))
pos = torch.arange(0, 12, dtype=int)
x[pos, 0::2] = torch.sin(pos.unsqueeze(1).float()@div_term.unsqueeze(0))
x[pos, 1::2] = torch.cos(pos.unsqueeze(1).float()@div_term.unsqueeze(0))


In [11]:
# for i in range(12):
#     x[i, 0::2] = torch.sin(i*div_term)
#     x[i, 1::2] = torch.cos(i*div_term)


In [12]:
x[0]

tensor([0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 

In [13]:
torch.sin(10000 ** (2 * ( a[::2] // 2) / 512))

tensor([ 8.4147e-01,  8.6069e-01,  8.7940e-01,  8.9746e-01,  9.1471e-01,
         9.3098e-01,  9.4609e-01,  9.5983e-01,  9.7198e-01,  9.8230e-01,
         9.9052e-01,  9.9637e-01,  9.9952e-01,  9.9967e-01,  9.9647e-01,
         9.8956e-01,  9.7855e-01,  9.6307e-01,  9.4270e-01,  9.1706e-01,
         8.8573e-01,  8.4834e-01,  8.0452e-01,  7.5393e-01,  6.9629e-01,
         6.3139e-01,  5.5910e-01,  4.7938e-01,  3.9234e-01,  2.9825e-01,
         1.9756e-01,  9.0939e-02, -2.0684e-02, -1.3610e-01, -2.5381e-01,
        -3.7194e-01, -4.8831e-01, -6.0034e-01, -7.0512e-01, -7.9943e-01,
        -8.7977e-01, -9.4244e-01, -9.8370e-01, -9.9989e-01, -9.8766e-01,
        -9.4419e-01, -8.6752e-01, -7.5686e-01, -6.1294e-01, -4.3836e-01,
        -2.3792e-01, -1.8849e-02,  2.0908e-01,  4.3363e-01,  6.4048e-01,
         8.1386e-01,  9.3763e-01,  9.9678e-01,  9.7917e-01,  8.7775e-01,
         6.9263e-01,  4.3308e-01,  1.1878e-01, -2.2002e-01, -5.4402e-01,
        -8.0847e-01, -9.6904e-01, -9.8963e-01, -8.5

In [14]:
a[1::2]


tensor([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,  27,
         29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,  53,  55,
         57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,  79,  81,  83,
         85,  87,  89,  91,  93,  95,  97,  99, 101, 103, 105, 107, 109, 111,
        113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139,
        141, 143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167,
        169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193, 195,
        197, 199, 201, 203, 205, 207, 209, 211, 213, 215, 217, 219, 221, 223,
        225, 227, 229, 231, 233, 235, 237, 239, 241, 243, 245, 247, 249, 251,
        253, 255, 257, 259, 261, 263, 265, 267, 269, 271, 273, 275, 277, 279,
        281, 283, 285, 287, 289, 291, 293, 295, 297, 299, 301, 303, 305, 307,
        309, 311, 313, 315, 317, 319, 321, 323, 325, 327, 329, 331, 333, 335,
        337, 339, 341, 343, 345, 347, 349, 351, 353, 355, 357, 3

In [15]:
class PositionalEncoding(torch.nn.Module):
    def __init__(self, d_model: int, dropout: float, seq_len: int):
        super().__init__()
        self.d_model = d_model
        self.seq_len = seq_len
        self.dropout = torch.nn.Dropout(dropout)

        # craete matrix of positional encoding
        pe = torch.zeros(self.seq_len, self.d_model) # shape = [seq_len, d_model]

        # create position matrix
        position = torch.arange(0, self.seq_len, dtype=torch.float32).unsqueeze(1) # shape = [seq_len, 1]
        # we calculate positional in log scale for stability
        div_term = torch.exp(torch.arange(0, self.d_model, 2).float() * (-math.log(10000.0) / self.d_model)) # shape = [d_model/2]
        # calculate positional encoding, apply sin to even index in the array; 2i and apply cos to odd index in the array; 2i+1
        # apply sine to even indices in the array; 2i
        pe[:, 0::2] = torch.sin(position * div_term)
        # apply cosine to odd indices in the array; 2i+1
        pe[:, 1::2] = torch.cos(position * div_term)

        # add batch dimension
        pe = pe.unsqueeze(0)

        # register buffer to save positional encoding (this is not model parameter)
        self.register_buffer('pe', pe)

    def forward(self, x):
        # x shape = [batch_size, seq_len, d_model]
        # pe shape = [1, seq_len, d_model]
        # add positional encoding to each sequence in batch
        # below code will broadcast pe over batch dimension
        x = x + self.pe[:, :x.shape[1], :].requires_grad_(False)

        return self.dropout(x)

In [16]:
pe = PositionalEncoding(seq_len=12, dropout=0., d_model=512)

In [17]:
y = torch.zeros(12, 512)
c = pe(y)[0]
c[1]

tensor([8.4147e-01, 5.4030e-01, 8.2186e-01, 5.6970e-01, 8.0196e-01, 5.9738e-01,
        7.8189e-01, 6.2342e-01, 7.6172e-01, 6.4791e-01, 7.4154e-01, 6.7091e-01,
        7.2141e-01, 6.9250e-01, 7.0140e-01, 7.1276e-01, 6.8156e-01, 7.3176e-01,
        6.6193e-01, 7.4956e-01, 6.4256e-01, 7.6624e-01, 6.2347e-01, 7.8185e-01,
        6.0469e-01, 7.9646e-01, 5.8626e-01, 8.1012e-01, 5.6818e-01, 8.2290e-01,
        5.5048e-01, 8.3485e-01, 5.3317e-01, 8.4601e-01, 5.1625e-01, 8.5644e-01,
        4.9974e-01, 8.6618e-01, 4.8364e-01, 8.7527e-01, 4.6795e-01, 8.8376e-01,
        4.5267e-01, 8.9168e-01, 4.3781e-01, 8.9907e-01, 4.2335e-01, 9.0596e-01,
        4.0931e-01, 9.1240e-01, 3.9567e-01, 9.1839e-01, 3.8242e-01, 9.2399e-01,
        3.6957e-01, 9.2920e-01, 3.5711e-01, 9.3406e-01, 3.4503e-01, 9.3859e-01,
        3.3332e-01, 9.4281e-01, 3.2197e-01, 9.4675e-01, 3.1098e-01, 9.5042e-01,
        3.0034e-01, 9.5383e-01, 2.9004e-01, 9.5701e-01, 2.8008e-01, 9.5998e-01,
        2.7043e-01, 9.6274e-01, 2.6110e-

In [22]:
for i in range(12):
    print(torch.all(c[i] == x[i]))

tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
