In [1]:
import torch
import einops

In [4]:
torch.arange(0, 3, dtype=torch.float32).unsqueeze(1)

tensor([[0.],
        [1.],
        [2.]])

In [12]:
a = einops.rearrange(torch.arange(0, 100), '(a b) -> a b', a=5, b=20)
a

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
         38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
         58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
         78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
         98, 99]])

In [10]:
a[:, 0::2]

tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
        [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
        [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
        [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [13]:

div_term = torch.exp(torch.arange(0, 100, 2) * (-torch.log(torch.tensor(10000.0)) / 100))

In [16]:
div_term.shape

torch.Size([50])

In [22]:
pe = torch.ones(1, 6, 100)
x = torch.zeros(32, 6, 100)

In [23]:
x = x + pe[:, :x.shape[1], :]

In [24]:
x

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1